// Code generated by goctl. DO NOT EDIT.
// Source: wecart.proto

package server

import (
	"context"

	"wecart/rpc/internal/logic"
	"wecart/rpc/internal/svc"
	"wecart/rpc/wecart"
)

type WecartServer struct {
	svcCtx *svc.ServiceContext
	wecart.UnimplementedWecartServer
}

func NewWecartServer(svcCtx *svc.ServiceContext) *WecartServer {
	return &WecartServer{
		svcCtx: svcCtx,
	}
}

func (s *WecartServer) PlaceAnOrderLogic(ctx context.Context, in *wecart.PlaceAnOrderReq) (*wecart.PlaceAnOrderResp, error) {
	l := logic.NewPlaceAnOrderLogicLogic(ctx, s.svcCtx)
	return l.PlaceAnOrderLogic(in)
}
