// Code generated by goctl. DO NOT EDIT.
// Source: wecart.proto

package wecartclient

import (
	"context"

	"wecart/rpc/wecart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	InitiateRequestReq       = wecart.InitiateRequestReq
	InitiateRequestResp      = wecart.InitiateRequestResp
	InitiateRequestResp_Data = wecart.InitiateRequestResp_Data

	Wecart interface {
		InitiateRequestLogic(ctx context.Context, in *InitiateRequestReq, opts ...grpc.CallOption) (*InitiateRequestResp, error)
	}

	defaultWecart struct {
		cli zrpc.Client
	}
)

func NewWecart(cli zrpc.Client) Wecart {
	return &defaultWecart{
		cli: cli,
	}
}

func (m *defaultWecart) InitiateRequestLogic(ctx context.Context, in *InitiateRequestReq, opts ...grpc.CallOption) (*InitiateRequestResp, error) {
	client := wecart.NewWecartClient(m.cli.Conn())
	return client.InitiateRequestLogic(ctx, in, opts...)
}
