// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modulation.proto

package pb // import "./pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeStatusRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusRequest) Reset()         { *m = CodeStatusRequest{} }
func (m *CodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CodeStatusRequest) ProtoMessage()    {}
func (*CodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_693c90bc09cba19f, []int{0}
}
func (m *CodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusRequest.Unmarshal(m, b)
}
func (m *CodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *CodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusRequest.Merge(dst, src)
}
func (m *CodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CodeStatusRequest.Size(m)
}
func (m *CodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusRequest proto.InternalMessageInfo

func (m *CodeStatusRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CodeStatusResponse struct {
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusResponse) Reset()         { *m = CodeStatusResponse{} }
func (m *CodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CodeStatusResponse) ProtoMessage()    {}
func (*CodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_693c90bc09cba19f, []int{1}
}
func (m *CodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusResponse.Unmarshal(m, b)
}
func (m *CodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusResponse.Marshal(b, m, deterministic)
}
func (dst *CodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusResponse.Merge(dst, src)
}
func (m *CodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CodeStatusResponse.Size(m)
}
func (m *CodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusResponse proto.InternalMessageInfo

func (m *CodeStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RequestConsumptionRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionRequest) Reset()         { *m = RequestConsumptionRequest{} }
func (m *RequestConsumptionRequest) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionRequest) ProtoMessage()    {}
func (*RequestConsumptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_693c90bc09cba19f, []int{2}
}
func (m *RequestConsumptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionRequest.Unmarshal(m, b)
}
func (m *RequestConsumptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionRequest.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionRequest.Merge(dst, src)
}
func (m *RequestConsumptionRequest) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionRequest.Size(m)
}
func (m *RequestConsumptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionRequest proto.InternalMessageInfo

func (m *RequestConsumptionRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RequestConsumptionResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionResponse) Reset()         { *m = RequestConsumptionResponse{} }
func (m *RequestConsumptionResponse) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionResponse) ProtoMessage()    {}
func (*RequestConsumptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_693c90bc09cba19f, []int{3}
}
func (m *RequestConsumptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionResponse.Unmarshal(m, b)
}
func (m *RequestConsumptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionResponse.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionResponse.Merge(dst, src)
}
func (m *RequestConsumptionResponse) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionResponse.Size(m)
}
func (m *RequestConsumptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionResponse proto.InternalMessageInfo

func (m *RequestConsumptionResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*CodeStatusRequest)(nil), "rpc.CodeStatusRequest")
	proto.RegisterType((*CodeStatusResponse)(nil), "rpc.CodeStatusResponse")
	proto.RegisterType((*RequestConsumptionRequest)(nil), "rpc.RequestConsumptionRequest")
	proto.RegisterType((*RequestConsumptionResponse)(nil), "rpc.RequestConsumptionResponse")
}

func init() { proto.RegisterFile("modulation.proto", fileDescriptor_modulation_693c90bc09cba19f) }

var fileDescriptor_modulation_693c90bc09cba19f = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcd, 0x4f, 0x29,
	0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a,
	0x48, 0x56, 0x52, 0xe5, 0x12, 0x74, 0xce, 0x4f, 0x49, 0x0d, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x0e,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x74, 0xb8, 0x84, 0x90, 0x95, 0x15, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0x83, 0x45, 0x24, 0x98, 0xc0, 0x4a, 0xa1, 0x3c, 0x25,
	0x5d, 0x2e, 0x49, 0xa8, 0x51, 0xce, 0xf9, 0x79, 0xc5, 0xa5, 0xb9, 0x05, 0x20, 0x5b, 0x71, 0x1b,
	0xae, 0xc7, 0x25, 0x85, 0x4d, 0x39, 0xd4, 0x12, 0x90, 0xfa, 0xa2, 0x1c, 0xb8, 0xfa, 0xa2, 0x1c,
	0xa3, 0x15, 0x8c, 0x5c, 0xdc, 0x25, 0x45, 0x89, 0x79, 0xc5, 0x69, 0xf9, 0x45, 0xb9, 0xa9, 0x45,
	0x42, 0x4e, 0x5c, 0xfc, 0x81, 0xa5, 0xa9, 0x45, 0x95, 0x08, 0x17, 0x0a, 0x89, 0xe9, 0x15, 0x15,
	0x24, 0xeb, 0x61, 0xf8, 0x4c, 0x4a, 0x1c, 0x43, 0x1c, 0x6a, 0x4b, 0x28, 0x97, 0x10, 0xa6, 0x1b,
	0x84, 0xe4, 0xc0, 0xca, 0x71, 0xfa, 0x45, 0x4a, 0x1e, 0xa7, 0x3c, 0xc4, 0x58, 0x27, 0xb6, 0x28,
	0x16, 0x3d, 0xfd, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x90, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x4f, 0xf6, 0xf5, 0xbe, 0x86, 0x01, 0x00, 0x00,
}
