// Code generated by goctl. DO NOT EDIT.
package types

type PlaceAnOrderReq struct {
	Appid       string `json:"appid"`
	Mchid       string `json:"mchid"`
	Description string `json:"description"`
	OutTradeNo  string `json:"outTradeNo"`
	Attach      string `json:"attach"`
	NotifyUrl   string `json:"notifyUrl"`
	Openid      string `json:"openid"`
}

type PlaceAnOrderResp struct {
	PlaceAnOrderResp []Data `json:"placeAnOrderResp"`
}

type Data struct {
	PrepayId  string `json:"prepayId"`
	Appid     string `json:"appid"`
	TimeStamp string `json:"timeStamp"`
	NonceStr  string `json:"nonceStr"`
	Package   string `json:"package"`
	SignType  string `json:"signType"`
	PaySign   string `json:"paySign"`
}
