// Code generated by goctl. DO NOT EDIT.
package types

type InitiateRequestReq struct {
	Url string `json:"url"`
}

type InitiateRequestResp struct {
	InitiateRequestResp []Data `json:"initiateRequestResp"`
}

type Data struct {
	Status string `json:"status"`
}
