// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modulation.proto

package modulation // import "./modulation"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeStatusRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusRequest) Reset()         { *m = CodeStatusRequest{} }
func (m *CodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CodeStatusRequest) ProtoMessage()    {}
func (*CodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{0}
}
func (m *CodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusRequest.Unmarshal(m, b)
}
func (m *CodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *CodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusRequest.Merge(dst, src)
}
func (m *CodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CodeStatusRequest.Size(m)
}
func (m *CodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusRequest proto.InternalMessageInfo

func (m *CodeStatusRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CodeStatusResponse struct {
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusResponse) Reset()         { *m = CodeStatusResponse{} }
func (m *CodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CodeStatusResponse) ProtoMessage()    {}
func (*CodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{1}
}
func (m *CodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusResponse.Unmarshal(m, b)
}
func (m *CodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusResponse.Marshal(b, m, deterministic)
}
func (dst *CodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusResponse.Merge(dst, src)
}
func (m *CodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CodeStatusResponse.Size(m)
}
func (m *CodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusResponse proto.InternalMessageInfo

func (m *CodeStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RequestConsumptionRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionRequest) Reset()         { *m = RequestConsumptionRequest{} }
func (m *RequestConsumptionRequest) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionRequest) ProtoMessage()    {}
func (*RequestConsumptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{2}
}
func (m *RequestConsumptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionRequest.Unmarshal(m, b)
}
func (m *RequestConsumptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionRequest.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionRequest.Merge(dst, src)
}
func (m *RequestConsumptionRequest) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionRequest.Size(m)
}
func (m *RequestConsumptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionRequest proto.InternalMessageInfo

func (m *RequestConsumptionRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RequestConsumptionResponse struct {
	DimensionalCode      string   `protobuf:"bytes,1,opt,name=dimensionalCode" json:"dimensionalCode,omitempty"`
	BarCode              string   `protobuf:"bytes,2,opt,name=barCode" json:"barCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionResponse) Reset()         { *m = RequestConsumptionResponse{} }
func (m *RequestConsumptionResponse) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionResponse) ProtoMessage()    {}
func (*RequestConsumptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{3}
}
func (m *RequestConsumptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionResponse.Unmarshal(m, b)
}
func (m *RequestConsumptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionResponse.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionResponse.Merge(dst, src)
}
func (m *RequestConsumptionResponse) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionResponse.Size(m)
}
func (m *RequestConsumptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionResponse proto.InternalMessageInfo

func (m *RequestConsumptionResponse) GetDimensionalCode() string {
	if m != nil {
		return m.DimensionalCode
	}
	return ""
}

func (m *RequestConsumptionResponse) GetBarCode() string {
	if m != nil {
		return m.BarCode
	}
	return ""
}

type OrderDetailsReq struct {
	OutRequestNo         string   `protobuf:"bytes,1,opt,name=outRequestNo" json:"outRequestNo,omitempty"`
	PayOutTradeNo        string   `protobuf:"bytes,2,opt,name=payOutTradeNo" json:"payOutTradeNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *OrderDetailsReq) Reset()         { *m = OrderDetailsReq{} }
func (m *OrderDetailsReq) String() string { return proto.CompactTextString(m) }
func (*OrderDetailsReq) ProtoMessage()    {}
func (*OrderDetailsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{4}
}
func (m *OrderDetailsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailsReq.Unmarshal(m, b)
}
func (m *OrderDetailsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailsReq.Marshal(b, m, deterministic)
}
func (dst *OrderDetailsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailsReq.Merge(dst, src)
}
func (m *OrderDetailsReq) XXX_Size() int {
	return xxx_messageInfo_OrderDetailsReq.Size(m)
}
func (m *OrderDetailsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailsReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailsReq proto.InternalMessageInfo

func (m *OrderDetailsReq) GetOutRequestNo() string {
	if m != nil {
		return m.OutRequestNo
	}
	return ""
}

func (m *OrderDetailsReq) GetPayOutTradeNo() string {
	if m != nil {
		return m.PayOutTradeNo
	}
	return ""
}

type OrderDetailsResp struct {
	PayStatus            string   `protobuf:"bytes,1,opt,name=payStatus" json:"payStatus,omitempty"`
	PayDate              string   `protobuf:"bytes,2,opt,name=payDate" json:"payDate,omitempty"`
	PayTime              string   `protobuf:"bytes,3,opt,name=payTime" json:"payTime,omitempty"`
	TotalFee             string   `protobuf:"bytes,4,opt,name=totalFee" json:"totalFee,omitempty"`
	PayCouponFee         string   `protobuf:"bytes,5,opt,name=payCouponFee" json:"payCouponFee,omitempty"`
	PayOutTradeNo        string   `protobuf:"bytes,6,opt,name=payOutTradeNo" json:"payOutTradeNo,omitempty"`
	PayErrDesc           string   `protobuf:"bytes,7,opt,name=payErrDesc" json:"payErrDesc,omitempty"`
	Uid                  string   `protobuf:"bytes,8,opt,name=uid" json:"uid,omitempty"`
	PayType              string   `protobuf:"bytes,9,opt,name=payType" json:"payType,omitempty"`
	PayTypeTradeNo       string   `protobuf:"bytes,10,opt,name=payTypeTradeNo" json:"payTypeTradeNo,omitempty"`
	OutRequestNo         string   `protobuf:"bytes,13,opt,name=outRequestNo" json:"outRequestNo,omitempty"`
	DimensionalCode      string   `protobuf:"bytes,11,opt,name=dimensionalCode" json:"dimensionalCode,omitempty"`
	BarCode              string   `protobuf:"bytes,12,opt,name=barCode" json:"barCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *OrderDetailsResp) Reset()         { *m = OrderDetailsResp{} }
func (m *OrderDetailsResp) String() string { return proto.CompactTextString(m) }
func (*OrderDetailsResp) ProtoMessage()    {}
func (*OrderDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_modulation_78f84da3fecd51ab, []int{5}
}
func (m *OrderDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailsResp.Unmarshal(m, b)
}
func (m *OrderDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailsResp.Marshal(b, m, deterministic)
}
func (dst *OrderDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailsResp.Merge(dst, src)
}
func (m *OrderDetailsResp) XXX_Size() int {
	return xxx_messageInfo_OrderDetailsResp.Size(m)
}
func (m *OrderDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailsResp proto.InternalMessageInfo

func (m *OrderDetailsResp) GetPayStatus() string {
	if m != nil {
		return m.PayStatus
	}
	return ""
}

func (m *OrderDetailsResp) GetPayDate() string {
	if m != nil {
		return m.PayDate
	}
	return ""
}

func (m *OrderDetailsResp) GetPayTime() string {
	if m != nil {
		return m.PayTime
	}
	return ""
}

func (m *OrderDetailsResp) GetTotalFee() string {
	if m != nil {
		return m.TotalFee
	}
	return ""
}

func (m *OrderDetailsResp) GetPayCouponFee() string {
	if m != nil {
		return m.PayCouponFee
	}
	return ""
}

func (m *OrderDetailsResp) GetPayOutTradeNo() string {
	if m != nil {
		return m.PayOutTradeNo
	}
	return ""
}

func (m *OrderDetailsResp) GetPayErrDesc() string {
	if m != nil {
		return m.PayErrDesc
	}
	return ""
}

func (m *OrderDetailsResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OrderDetailsResp) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *OrderDetailsResp) GetPayTypeTradeNo() string {
	if m != nil {
		return m.PayTypeTradeNo
	}
	return ""
}

func (m *OrderDetailsResp) GetOutRequestNo() string {
	if m != nil {
		return m.OutRequestNo
	}
	return ""
}

func (m *OrderDetailsResp) GetDimensionalCode() string {
	if m != nil {
		return m.DimensionalCode
	}
	return ""
}

func (m *OrderDetailsResp) GetBarCode() string {
	if m != nil {
		return m.BarCode
	}
	return ""
}

func init() {
	proto.RegisterType((*CodeStatusRequest)(nil), "modulation.CodeStatusRequest")
	proto.RegisterType((*CodeStatusResponse)(nil), "modulation.CodeStatusResponse")
	proto.RegisterType((*RequestConsumptionRequest)(nil), "modulation.RequestConsumptionRequest")
	proto.RegisterType((*RequestConsumptionResponse)(nil), "modulation.RequestConsumptionResponse")
	proto.RegisterType((*OrderDetailsReq)(nil), "modulation.OrderDetailsReq")
	proto.RegisterType((*OrderDetailsResp)(nil), "modulation.OrderDetailsResp")
}

func init() { proto.RegisterFile("modulation.proto", fileDescriptor_modulation_78f84da3fecd51ab) }

var fileDescriptor_modulation_78f84da3fecd51ab = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xd6, 0x6e, 0xa1, 0xbb, 0x1d, 0xda, 0x6d, 0x77, 0x0e, 0x28, 0x84, 0x65, 0x85, 0x22, 0xb6,
	0xea, 0x01, 0x8a, 0x04, 0x6f, 0x40, 0x0b, 0x27, 0xd4, 0x42, 0xe9, 0x09, 0x2e, 0xb8, 0x89, 0x85,
	0x22, 0x25, 0xb1, 0xf1, 0xcf, 0xc1, 0x2f, 0xc2, 0x23, 0xf0, 0x9c, 0x2b, 0xa7, 0xce, 0x5f, 0x93,
	0xa8, 0x37, 0xcf, 0x37, 0x9f, 0x67, 0xbe, 0xc9, 0x7c, 0x0e, 0xcc, 0x52, 0x16, 0xe9, 0x84, 0xa8,
	0x98, 0x65, 0x4b, 0x2e, 0x98, 0x62, 0x08, 0x15, 0x12, 0x3c, 0xc0, 0xed, 0x8a, 0x45, 0xf4, 0x87,
	0x22, 0x4a, 0xcb, 0x1d, 0xfd, 0xab, 0xa9, 0x54, 0x38, 0x83, 0x81, 0x8e, 0x23, 0xef, 0xe2, 0xf5,
	0xc5, 0x62, 0xb4, 0xb3, 0xc7, 0xe0, 0x2d, 0x60, 0x9d, 0x26, 0x39, 0xcb, 0x24, 0xc5, 0xe7, 0x30,
	0x94, 0x39, 0xe2, 0x5d, 0xe6, 0x54, 0x17, 0x05, 0xef, 0xe0, 0x85, 0x2b, 0xb5, 0x62, 0x99, 0xd4,
	0x29, 0xb7, 0xad, 0xfa, 0x8b, 0xff, 0x06, 0xbf, 0x8b, 0xee, 0x9a, 0x2c, 0x60, 0x1a, 0xc5, 0x29,
	0xcd, 0x64, 0xcc, 0x32, 0x92, 0x58, 0x15, 0xee, 0xee, 0x29, 0x8c, 0x1e, 0x5c, 0x1d, 0x88, 0xc8,
	0x19, 0x47, 0x3d, 0x45, 0x18, 0xfc, 0x82, 0xe9, 0x56, 0x44, 0x54, 0xac, 0xa9, 0x22, 0x71, 0x62,
	0xe7, 0xc4, 0x00, 0xc6, 0x4c, 0x2b, 0xd7, 0x77, 0xc3, 0x5c, 0xcd, 0x06, 0x86, 0x6f, 0x60, 0xc2,
	0x89, 0xd9, 0x6a, 0xb5, 0x17, 0x24, 0xa2, 0x1b, 0xe6, 0xca, 0x36, 0xc1, 0xe0, 0xff, 0x00, 0x66,
	0xcd, 0xea, 0x92, 0xe3, 0x1d, 0x8c, 0x38, 0x31, 0xc7, 0xef, 0xe5, 0x6a, 0x57, 0x80, 0x55, 0xca,
	0x89, 0x59, 0x13, 0x55, 0x2a, 0x75, 0xa1, 0xcb, 0xec, 0xe3, 0x94, 0x7a, 0x83, 0x32, 0x63, 0x43,
	0xf4, 0xe1, 0x5a, 0x31, 0x45, 0x92, 0x2f, 0x94, 0x7a, 0x4f, 0xf2, 0x54, 0x19, 0xdb, 0x61, 0x38,
	0x31, 0x2b, 0xa6, 0x39, 0xcb, 0x6c, 0xfe, 0xe9, 0x71, 0x98, 0x3a, 0xd6, 0x1e, 0x66, 0xd8, 0x31,
	0x0c, 0xde, 0x03, 0x70, 0x62, 0x3e, 0x0b, 0xb1, 0xa6, 0x32, 0xf4, 0xae, 0x72, 0x4a, 0x0d, 0x29,
	0xb6, 0x77, 0x5d, 0x6e, 0xaf, 0x50, 0x6c, 0x38, 0xf5, 0x46, 0x95, 0x62, 0xc3, 0x29, 0xce, 0xe1,
	0xc6, 0x1d, 0x8b, 0x96, 0x90, 0x13, 0x4e, 0xd0, 0xd6, 0x2a, 0x26, 0x1d, 0xab, 0xe8, 0x70, 0xc1,
	0xb3, 0xb3, 0x2e, 0x18, 0x37, 0x5c, 0xf0, 0xe1, 0xdf, 0x25, 0x4c, 0x2a, 0xeb, 0xef, 0x78, 0x88,
	0xdf, 0x60, 0xfa, 0x5d, 0x53, 0x61, 0x2a, 0x6f, 0xe3, 0xab, 0x65, 0xed, 0xbd, 0xb4, 0x9e, 0x86,
	0x7f, 0xdf, 0x97, 0x76, 0x6e, 0x0d, 0x01, 0xdb, 0x5e, 0xc6, 0x87, 0xfa, 0xad, 0xde, 0xa7, 0xe1,
	0xcf, 0xcf, 0xd1, 0x5c, 0x93, 0x0d, 0xdc, 0xd6, 0x0d, 0xf7, 0x95, 0xfd, 0x89, 0x43, 0x7c, 0x59,
	0xbf, 0x7c, 0xe2, 0x76, 0xff, 0xae, 0x3f, 0x29, 0xf9, 0xa7, 0x9b, 0x9f, 0xe3, 0xe5, 0xfb, 0x8a,
	0x70, 0x18, 0xe6, 0xff, 0x89, 0x8f, 0x8f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0xce, 0x45, 0xcd,
	0x3b, 0x04, 0x00, 0x00,
}
