// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transform.proto

package pb // import "./pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExpandReq struct {
	Shorten              string   `protobuf:"bytes,1,opt,name=shorten" json:"shorten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ExpandReq) Reset()         { *m = ExpandReq{} }
func (m *ExpandReq) String() string { return proto.CompactTextString(m) }
func (*ExpandReq) ProtoMessage()    {}
func (*ExpandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{0}
}
func (m *ExpandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandReq.Unmarshal(m, b)
}
func (m *ExpandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandReq.Marshal(b, m, deterministic)
}
func (dst *ExpandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandReq.Merge(dst, src)
}
func (m *ExpandReq) XXX_Size() int {
	return xxx_messageInfo_ExpandReq.Size(m)
}
func (m *ExpandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandReq proto.InternalMessageInfo

func (m *ExpandReq) GetShorten() string {
	if m != nil {
		return m.Shorten
	}
	return ""
}

type ExpandResp struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ExpandResp) Reset()         { *m = ExpandResp{} }
func (m *ExpandResp) String() string { return proto.CompactTextString(m) }
func (*ExpandResp) ProtoMessage()    {}
func (*ExpandResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{1}
}
func (m *ExpandResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandResp.Unmarshal(m, b)
}
func (m *ExpandResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandResp.Marshal(b, m, deterministic)
}
func (dst *ExpandResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandResp.Merge(dst, src)
}
func (m *ExpandResp) XXX_Size() int {
	return xxx_messageInfo_ExpandResp.Size(m)
}
func (m *ExpandResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandResp proto.InternalMessageInfo

func (m *ExpandResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortenReq struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ShortenReq) Reset()         { *m = ShortenReq{} }
func (m *ShortenReq) String() string { return proto.CompactTextString(m) }
func (*ShortenReq) ProtoMessage()    {}
func (*ShortenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{2}
}
func (m *ShortenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenReq.Unmarshal(m, b)
}
func (m *ShortenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenReq.Marshal(b, m, deterministic)
}
func (dst *ShortenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenReq.Merge(dst, src)
}
func (m *ShortenReq) XXX_Size() int {
	return xxx_messageInfo_ShortenReq.Size(m)
}
func (m *ShortenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenReq proto.InternalMessageInfo

func (m *ShortenReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortenResp struct {
	Shorten              string   `protobuf:"bytes,1,opt,name=shorten" json:"shorten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ShortenResp) Reset()         { *m = ShortenResp{} }
func (m *ShortenResp) String() string { return proto.CompactTextString(m) }
func (*ShortenResp) ProtoMessage()    {}
func (*ShortenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{3}
}
func (m *ShortenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenResp.Unmarshal(m, b)
}
func (m *ShortenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenResp.Marshal(b, m, deterministic)
}
func (dst *ShortenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenResp.Merge(dst, src)
}
func (m *ShortenResp) XXX_Size() int {
	return xxx_messageInfo_ShortenResp.Size(m)
}
func (m *ShortenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenResp.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenResp proto.InternalMessageInfo

func (m *ShortenResp) GetShorten() string {
	if m != nil {
		return m.Shorten
	}
	return ""
}

type CodeStatusRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusRequest) Reset()         { *m = CodeStatusRequest{} }
func (m *CodeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CodeStatusRequest) ProtoMessage()    {}
func (*CodeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{4}
}
func (m *CodeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusRequest.Unmarshal(m, b)
}
func (m *CodeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusRequest.Marshal(b, m, deterministic)
}
func (dst *CodeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusRequest.Merge(dst, src)
}
func (m *CodeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CodeStatusRequest.Size(m)
}
func (m *CodeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusRequest proto.InternalMessageInfo

func (m *CodeStatusRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type CodeStatusResponse struct {
	Status               string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CodeStatusResponse) Reset()         { *m = CodeStatusResponse{} }
func (m *CodeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CodeStatusResponse) ProtoMessage()    {}
func (*CodeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{5}
}
func (m *CodeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeStatusResponse.Unmarshal(m, b)
}
func (m *CodeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeStatusResponse.Marshal(b, m, deterministic)
}
func (dst *CodeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeStatusResponse.Merge(dst, src)
}
func (m *CodeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CodeStatusResponse.Size(m)
}
func (m *CodeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeStatusResponse proto.InternalMessageInfo

func (m *CodeStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RequestConsumptionRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionRequest) Reset()         { *m = RequestConsumptionRequest{} }
func (m *RequestConsumptionRequest) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionRequest) ProtoMessage()    {}
func (*RequestConsumptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{6}
}
func (m *RequestConsumptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionRequest.Unmarshal(m, b)
}
func (m *RequestConsumptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionRequest.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionRequest.Merge(dst, src)
}
func (m *RequestConsumptionRequest) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionRequest.Size(m)
}
func (m *RequestConsumptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionRequest proto.InternalMessageInfo

func (m *RequestConsumptionRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RequestConsumptionResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RequestConsumptionResponse) Reset()         { *m = RequestConsumptionResponse{} }
func (m *RequestConsumptionResponse) String() string { return proto.CompactTextString(m) }
func (*RequestConsumptionResponse) ProtoMessage()    {}
func (*RequestConsumptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_transform_50344755934ac4c3, []int{7}
}
func (m *RequestConsumptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestConsumptionResponse.Unmarshal(m, b)
}
func (m *RequestConsumptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestConsumptionResponse.Marshal(b, m, deterministic)
}
func (dst *RequestConsumptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestConsumptionResponse.Merge(dst, src)
}
func (m *RequestConsumptionResponse) XXX_Size() int {
	return xxx_messageInfo_RequestConsumptionResponse.Size(m)
}
func (m *RequestConsumptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestConsumptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestConsumptionResponse proto.InternalMessageInfo

func (m *RequestConsumptionResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ExpandReq)(nil), "transform.expandReq")
	proto.RegisterType((*ExpandResp)(nil), "transform.expandResp")
	proto.RegisterType((*ShortenReq)(nil), "transform.shortenReq")
	proto.RegisterType((*ShortenResp)(nil), "transform.shortenResp")
	proto.RegisterType((*CodeStatusRequest)(nil), "transform.CodeStatusRequest")
	proto.RegisterType((*CodeStatusResponse)(nil), "transform.CodeStatusResponse")
	proto.RegisterType((*RequestConsumptionRequest)(nil), "transform.RequestConsumptionRequest")
	proto.RegisterType((*RequestConsumptionResponse)(nil), "transform.RequestConsumptionResponse")
}

func init() { proto.RegisterFile("transform.proto", fileDescriptor_transform_50344755934ac4c3) }

var fileDescriptor_transform_50344755934ac4c3 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xd9, 0x55, 0x2a, 0x9d, 0x3d, 0xac, 0x0e, 0xba, 0xd4, 0xa0, 0x22, 0xc5, 0xa2, 0x07,
	0xad, 0xa0, 0x08, 0x9e, 0xdd, 0xbb, 0x60, 0xbd, 0x79, 0xeb, 0xd2, 0x88, 0x05, 0x37, 0xc9, 0x66,
	0x12, 0xd0, 0xc7, 0xf2, 0x0d, 0xa5, 0xdd, 0x34, 0x2d, 0xb4, 0xd5, 0x5b, 0x33, 0xff, 0xd7, 0x7f,
	0xc8, 0x47, 0x60, 0x6e, 0x74, 0x2e, 0xe8, 0x5d, 0xea, 0x75, 0xaa, 0xb4, 0x34, 0x12, 0x43, 0x3f,
	0x88, 0x13, 0x08, 0xf9, 0x97, 0xca, 0x45, 0x91, 0xf1, 0x0d, 0x46, 0xb0, 0x47, 0x1f, 0x52, 0x1b,
	0x2e, 0xa2, 0xc9, 0xf9, 0xe4, 0x2a, 0xcc, 0x9a, 0x63, 0x7c, 0x06, 0xd0, 0x60, 0xa4, 0x70, 0x1f,
	0x76, 0xac, 0xfe, 0x74, 0x4c, 0xf5, 0x59, 0xe5, 0x0e, 0xad, 0x7a, 0xfa, 0xf9, 0x25, 0xcc, 0x7c,
	0x4e, 0xea, 0x8f, 0x45, 0x09, 0x1c, 0x2c, 0x65, 0xc1, 0x5f, 0x4d, 0x6e, 0x2c, 0x65, 0x7c, 0x63,
	0x39, 0x99, 0xba, 0xaf, 0x2c, 0x7c, 0x5f, 0x59, 0xc4, 0xd7, 0x80, 0x5d, 0x8c, 0x94, 0x14, 0xc4,
	0x71, 0x01, 0x01, 0xd5, 0x93, 0x68, 0x5a, 0xa3, 0xee, 0x14, 0xdf, 0xc0, 0xb1, 0xab, 0x5a, 0x4a,
	0x41, 0x76, 0xad, 0x4c, 0x29, 0xc5, 0x78, 0x79, 0x0a, 0x6c, 0x08, 0x77, 0x4b, 0x7a, 0x97, 0xbb,
	0xfb, 0x99, 0xc2, 0xcc, 0x1b, 0xe5, 0x1a, 0x1f, 0x20, 0xd8, 0xca, 0xc2, 0xc3, 0xb4, 0x55, 0xef,
	0x35, 0xb3, 0xa3, 0x81, 0x29, 0x29, 0x7c, 0xf4, 0x52, 0xb0, 0x4b, 0xb4, 0x5e, 0xd9, 0x62, 0x68,
	0x4c, 0x0a, 0x9f, 0x61, 0xfe, 0x62, 0xb9, 0xfe, 0x6e, 0x95, 0xe0, 0x49, 0x07, 0xed, 0x09, 0x65,
	0xa7, 0x23, 0xa9, 0xbb, 0x62, 0x0e, 0xd8, 0x17, 0x80, 0x17, 0x9d, 0x9f, 0x46, 0x75, 0xb2, 0xe4,
	0x1f, 0x6a, 0xbb, 0xe2, 0x29, 0x78, 0xdb, 0x4d, 0x6f, 0xd5, 0x6a, 0x15, 0xd4, 0x2f, 0xf2, 0xfe,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x56, 0x83, 0x78, 0xa4, 0x02, 0x00, 0x00,
}
