// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: wecart.proto

package wecart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceAnOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid       string `protobuf:"bytes,1,opt,name=Appid,proto3" json:"Appid,omitempty"`
	Mchid       string `protobuf:"bytes,2,opt,name=Mchid,proto3" json:"Mchid,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	OutTradeNo  string `protobuf:"bytes,4,opt,name=OutTradeNo,proto3" json:"OutTradeNo,omitempty"`
	Attach      string `protobuf:"bytes,5,opt,name=Attach,proto3" json:"Attach,omitempty"`
	NotifyUrl   string `protobuf:"bytes,6,opt,name=NotifyUrl,proto3" json:"NotifyUrl,omitempty"`
	Openid      string `protobuf:"bytes,7,opt,name=Openid,proto3" json:"Openid,omitempty"`
}

func (x *PlaceAnOrderReq) Reset() {
	*x = PlaceAnOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceAnOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceAnOrderReq) ProtoMessage() {}

func (x *PlaceAnOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceAnOrderReq.ProtoReflect.Descriptor instead.
func (*PlaceAnOrderReq) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceAnOrderReq) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *PlaceAnOrderReq) GetMchid() string {
	if x != nil {
		return x.Mchid
	}
	return ""
}

func (x *PlaceAnOrderReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlaceAnOrderReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *PlaceAnOrderReq) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *PlaceAnOrderReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PlaceAnOrderReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type PlaceAnOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PlaceAnOrderResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PlaceAnOrderResp) Reset() {
	*x = PlaceAnOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceAnOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceAnOrderResp) ProtoMessage() {}

func (x *PlaceAnOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceAnOrderResp.ProtoReflect.Descriptor instead.
func (*PlaceAnOrderResp) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceAnOrderResp) GetData() []*PlaceAnOrderResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type PlaceAnOrderResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrepayId  string `protobuf:"bytes,1,opt,name=PrepayId,proto3" json:"PrepayId,omitempty"`
	Appid     string `protobuf:"bytes,2,opt,name=Appid,proto3" json:"Appid,omitempty"`
	TimeStamp string `protobuf:"bytes,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	NonceStr  string `protobuf:"bytes,4,opt,name=NonceStr,proto3" json:"NonceStr,omitempty"`
	Package   string `protobuf:"bytes,5,opt,name=Package,proto3" json:"Package,omitempty"`
	SignType  string `protobuf:"bytes,6,opt,name=SignType,proto3" json:"SignType,omitempty"`
	PaySign   string `protobuf:"bytes,7,opt,name=PaySign,proto3" json:"PaySign,omitempty"`
}

func (x *PlaceAnOrderResp_Data) Reset() {
	*x = PlaceAnOrderResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceAnOrderResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceAnOrderResp_Data) ProtoMessage() {}

func (x *PlaceAnOrderResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceAnOrderResp_Data.ProtoReflect.Descriptor instead.
func (*PlaceAnOrderResp_Data) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PlaceAnOrderResp_Data) GetPrepayId() string {
	if x != nil {
		return x.PrepayId
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *PlaceAnOrderResp_Data) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

var File_wecart_proto protoreflect.FileDescriptor

var file_wecart_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70,
	0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x4d, 0x63, 0x68, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4d, 0x63, 0x68, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x75,
	0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x22, 0x8a, 0x02, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x65, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xc2,
	0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x53, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x53,
	0x69, 0x67, 0x6e, 0x32, 0x50, 0x0a, 0x06, 0x57, 0x65, 0x63, 0x61, 0x72, 0x74, 0x12, 0x46, 0x0a,
	0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x12, 0x17, 0x2e, 0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x77, 0x65,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x77, 0x65, 0x63, 0x61, 0x72,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wecart_proto_rawDescOnce sync.Once
	file_wecart_proto_rawDescData = file_wecart_proto_rawDesc
)

func file_wecart_proto_rawDescGZIP() []byte {
	file_wecart_proto_rawDescOnce.Do(func() {
		file_wecart_proto_rawDescData = protoimpl.X.CompressGZIP(file_wecart_proto_rawDescData)
	})
	return file_wecart_proto_rawDescData
}

var file_wecart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wecart_proto_goTypes = []interface{}{
	(*PlaceAnOrderReq)(nil),       // 0: wecart.PlaceAnOrderReq
	(*PlaceAnOrderResp)(nil),      // 1: wecart.PlaceAnOrderResp
	(*PlaceAnOrderResp_Data)(nil), // 2: wecart.PlaceAnOrderResp.Data
}
var file_wecart_proto_depIdxs = []int32{
	2, // 0: wecart.PlaceAnOrderResp.data:type_name -> wecart.PlaceAnOrderResp.Data
	0, // 1: wecart.Wecart.PlaceAnOrderLogic:input_type -> wecart.PlaceAnOrderReq
	1, // 2: wecart.Wecart.PlaceAnOrderLogic:output_type -> wecart.PlaceAnOrderResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wecart_proto_init() }
func file_wecart_proto_init() {
	if File_wecart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wecart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceAnOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wecart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceAnOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wecart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceAnOrderResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wecart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wecart_proto_goTypes,
		DependencyIndexes: file_wecart_proto_depIdxs,
		MessageInfos:      file_wecart_proto_msgTypes,
	}.Build()
	File_wecart_proto = out.File
	file_wecart_proto_rawDesc = nil
	file_wecart_proto_goTypes = nil
	file_wecart_proto_depIdxs = nil
}
