// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.4
// source: wecart.proto

package wecart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *InitiateRequestReq) Reset() {
	*x = InitiateRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRequestReq) ProtoMessage() {}

func (x *InitiateRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRequestReq.ProtoReflect.Descriptor instead.
func (*InitiateRequestReq) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateRequestReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type InitiateRequestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*InitiateRequestResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *InitiateRequestResp) Reset() {
	*x = InitiateRequestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRequestResp) ProtoMessage() {}

func (x *InitiateRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRequestResp.ProtoReflect.Descriptor instead.
func (*InitiateRequestResp) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateRequestResp) GetData() []*InitiateRequestResp_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InitiateRequestResp_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *InitiateRequestResp_Data) Reset() {
	*x = InitiateRequestResp_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wecart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitiateRequestResp_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRequestResp_Data) ProtoMessage() {}

func (x *InitiateRequestResp_Data) ProtoReflect() protoreflect.Message {
	mi := &file_wecart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRequestResp_Data.ProtoReflect.Descriptor instead.
func (*InitiateRequestResp_Data) Descriptor() ([]byte, []int) {
	return file_wecart_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitiateRequestResp_Data) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_wecart_proto protoreflect.FileDescriptor

var file_wecart_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x22, 0x26, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x6b,
	0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x59, 0x0a, 0x06, 0x57,
	0x65, 0x63, 0x61, 0x72, 0x74, 0x12, 0x4f, 0x0a, 0x14, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x1a, 0x2e,
	0x77, 0x65, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x65, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x77, 0x65, 0x63, 0x61,
	0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wecart_proto_rawDescOnce sync.Once
	file_wecart_proto_rawDescData = file_wecart_proto_rawDesc
)

func file_wecart_proto_rawDescGZIP() []byte {
	file_wecart_proto_rawDescOnce.Do(func() {
		file_wecart_proto_rawDescData = protoimpl.X.CompressGZIP(file_wecart_proto_rawDescData)
	})
	return file_wecart_proto_rawDescData
}

var file_wecart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wecart_proto_goTypes = []interface{}{
	(*InitiateRequestReq)(nil),       // 0: wecart.InitiateRequestReq
	(*InitiateRequestResp)(nil),      // 1: wecart.InitiateRequestResp
	(*InitiateRequestResp_Data)(nil), // 2: wecart.InitiateRequestResp.Data
}
var file_wecart_proto_depIdxs = []int32{
	2, // 0: wecart.InitiateRequestResp.data:type_name -> wecart.InitiateRequestResp.Data
	0, // 1: wecart.Wecart.InitiateRequestLogic:input_type -> wecart.InitiateRequestReq
	1, // 2: wecart.Wecart.InitiateRequestLogic:output_type -> wecart.InitiateRequestResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wecart_proto_init() }
func file_wecart_proto_init() {
	if File_wecart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wecart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wecart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateRequestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wecart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitiateRequestResp_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wecart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wecart_proto_goTypes,
		DependencyIndexes: file_wecart_proto_depIdxs,
		MessageInfos:      file_wecart_proto_msgTypes,
	}.Build()
	File_wecart_proto = out.File
	file_wecart_proto_rawDesc = nil
	file_wecart_proto_goTypes = nil
	file_wecart_proto_depIdxs = nil
}
