// Code generated by goctl. DO NOT EDIT.
package types

type CodeStatusRequest struct {
	Uid string `json:"uid"`
}

type CodeStatusResponse struct {
	Status string `json:"status"`
}

type RequestConsumptionRequest struct {
	Uid string `json:"uid"`
}

type RequestConsumptionResponse struct {
	Url string `json:"url"`
}
