// Code generated by goctl. DO NOT EDIT.
package types

type CodeStatusRequest struct {
	Uid string `json:"uid"`
}

type CodeStatusResponse struct {
	Status string `json:"status"`
}

type RequestConsumptionRequest struct {
	Uid string `json:"uid"`
}

type RequestConsumptionResponse struct {
	Url string `json:"url"`
}

type OrderDetailsReq struct {
	OutRequestNo  string `form:"outRequestNo"`
	PayOutTradeNo string `form:"payOutTradeNo"`
}

type OrderDetailsResp struct {
	PayStatus      string `json:"payStatus"`
	PayDate        string `json:"payDate"`
	PayTime        string `json:"payTime"`
	TotalFee       string `json:"totalFee"`
	PayCouponFee   string `json:"payCouponFee"`
	PayOutTradeNo  string `json:"payOutTradeNo"`
	PayErrDesc     string `json:"payErrDesc"`
	Uid            string `json:"uid"`
	PayType        string `json:"payType"`
	PayTypeTradeNo string `json:"payTypeTradeNo"`
}
