// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}
