// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}

type CodeStatusRequest struct {
	Uid string `json:"uid"`
}

type CodeStatusResponse struct {
	Status string `json:"status"`
}

type RequestConsumptionRequest struct {
	Uid string `json:"uid"`
}

type RequestConsumptionResponse struct {
	Url string `json:"url"`
}
