// Code generated by goctl. DO NOT EDIT.
package types

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}

type QueryConsumeStatusReq struct {
	Uid string `form:"uid"`
}
type QueryConsumeStatusResp struct {
	Code   int     `json:"code"`
	Errmsg string  `json:"errmsg"`
	Data   *[]Data `json:"data"`
	Status string `json:"status"`
}
type Data struct {
	Status string `json:"status"`
}
