// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/QueryCodeStatus",
				Handler: QueryCodeStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/RequestConsumption",
				Handler: RequestConsumptionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/GetPaymentRequest",
				Handler: GetPaymentRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/CheckNonSecret",
				Handler: CheckNonSecretHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/ConsumptionRepository",
				Handler: ConsumptionRepositoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xfmcode/PaymentAgreement",
				Handler: PaymentAgreementHandler(serverCtx),
			},
		},
	)
}
