// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lcclicheng/XFMcode/xfm_code/service/interface/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/expand",
				Handler: ExpandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/QueryCodeStatus",
				Handler: QueryCodeStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/RequestConsumption",
				Handler: RequestConsumptionHandler(serverCtx),
			},
		},
	)
}
